services:
  claude-code:
    build:
      context: .
      dockerfile: Dockerfile
    image: claude-code:latest
    container_name: claude-code
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "63980:8080"          # 主要端口
      - "64000-65000:64000-65000"  # 备用端口范围
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    tty: true
    stdin_open: true
